//
// Created by saeed on 12/22/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_GEEKSFORGEEKSLONGESTINCREASINGSUBSEQUENCE_H
#define LEETCODEPROBLEMSCMAKE_GEEKSFORGEEKSLONGESTINCREASINGSUBSEQUENCE_H
#include <vector>


class GeeksForGeeksLongestIncreasingSubsequence {
    int lis(std::vector<int>& arr);
};


#endif //LEETCODEPROBLEMSCMAKE_GEEKSFORGEEKSLONGESTINCREASINGSUBSEQUENCE_H