//
// Created by saeed on 11/17/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1437CHECKIFALL1SAREATLEASTLENGTHKPLACESAWAY_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1437CHECKIFALL1SAREATLEASTLENGTHKPLACESAWAY_H
#include <vector>


class LeetCode1437CheckIfAll1sAreAtLeastLengthKPlacesAway {
private:
    bool kLengthApart(std::vector<int>& nums, int k);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1437CHECKIFALL1SAREATLEASTLENGTHKPLACESAWAY_H