//
// Created by Saeed Jannati on 2/1/2026 A.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3010DIVIDEANARRAYINTOSUBARRAYSWITHMINIMUMCOSTI_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3010DIVIDEANARRAYINTOSUBARRAYSWITHMINIMUMCOSTI_H
#include <vector>


class LeetCode3010DivideAnArrayIntoSubarraysWithMinimumCostI {
    int minimumCost(std::vector<int>& nums);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3010DIVIDEANARRAYINTOSUBARRAYSWITHMINIMUMCOSTI_H