//
// Created by saeed on 10/31/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3289THETWOSNEAKYNUMBERSOFDIGITVILLE_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3289THETWOSNEAKYNUMBERSOFDIGITVILLE_H
#include <vector>


class LeetCode3289TheTwoSneakyNumbersOfDigitville {
    std::vector<int> getSneakyNumbers(std::vector<int>& nums);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3289THETWOSNEAKYNUMBERSOFDIGITVILLE_H