//
// Created by Saeed Jannati on 6/1/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE2144MINIMUMCOSTOFBUYINGCANDIESWITHDISCOUNT_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE2144MINIMUMCOSTOFBUYINGCANDIESWITHDISCOUNT_H
#include <vector>


class LeetCode2144MinimumCostOfBuyingCandiesWithDiscount {
private:
    int minimumCost(std::vector<int>& cost);
};




#endif //LEETCODEPROBLEMSCMAKE_LEETCODE2144MINIMUMCOSTOFBUYINGCANDIESWITHDISCOUNT_H
