//
// Created by Saeed Jannati on 2/23/2026 A.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1461CHECKIFASTRINGCONTAINSALLBINARYCODESOFSIZEK_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1461CHECKIFASTRINGCONTAINSALLBINARYCODESOFSIZEK_H
#include <string>


class LeetCode1461CheckIfAStringContainsAllBinaryCodesOfSizeK {
    bool hasAllCodes(std::string s, int k);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1461CHECKIFASTRINGCONTAINSALLBINARYCODESOFSIZEK_H