//
// Created by Saeed Jannati on 6/28/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1846MAXIMUMELEMENTAFTERDECREASINGANDREARRANGING_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1846MAXIMUMELEMENTAFTERDECREASINGANDREARRANGING_H
#include <vector>


class LeetCode1846MaximumElementAfterDecreasingAndRearranging {
private:
    int maximumElementAfterDecrementingAndRearranging(std::vector<int>& arr);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1846MAXIMUMELEMENTAFTERDECREASINGANDREARRANGING_H