//
// Created by saeed on 6/12/25.
//

#ifndef LEETCODE3423MAXIMUMDIFFERENCEBETWEENADJACENTELEMENTSINACIRCULARARRAY_H
#define LEETCODE3423MAXIMUMDIFFERENCEBETWEENADJACENTELEMENTSINACIRCULARARRAY_H
#include <vector>


class LeetCode3423MaximumDifferenceBetweenAdjacentElementsInACircularArray {
    int maxAdjacentDistance(std::vector<int>& nums);
};



#endif //LEETCODE3423MAXIMUMDIFFERENCEBETWEENADJACENTELEMENTSINACIRCULARARRAY_H
