//
// Created by saeed on 10/18/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3397MAXIMUMNUMBEROFDISTINCTELEMENTSAFTEROPERATIONS_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3397MAXIMUMNUMBEROFDISTINCTELEMENTSAFTEROPERATIONS_H
#include <vector>


class LeetCode3397MaximumNumberOfDistinctElementsAfterOperations {
private:
    int maxDistinctElements(std::vector<int>& nums, int k) ;
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3397MAXIMUMNUMBEROFDISTINCTELEMENTSAFTEROPERATIONS_H