//
// Created by saeed on 12/28/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1351COUNTNEGATIVENUMBERSINASORTEDMATRIX_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1351COUNTNEGATIVENUMBERSINASORTEDMATRIX_H
#include <vector>


class LeetCode1351CountNegativeNumbersInASortedMatrix {
    int countNegatives(std::vector<std::vector<int>>& grid);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1351COUNTNEGATIVENUMBERSINASORTEDMATRIX_H