//
// Created by saeed on 2/6/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3634MINIMUMREMOVALSTOBALANCEARRAY_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3634MINIMUMREMOVALSTOBALANCEARRAY_H
#include <vector>


class LeetCode3634MinimumRemovalsToBalanceArray {
    int minRemoval(std::vector<int>& nums, int k) ;
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3634MINIMUMREMOVALSTOBALANCEARRAY_H