//
// Created by saeed on 5/27/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3121COUNTTHENUMBEROFSPECIALCHARACTERSII_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3121COUNTTHENUMBEROFSPECIALCHARACTERSII_H
#include <string>


class LeetCode3121CountTheNumberOfSpecialCharactersII {
private:
    int numberOfSpecialChars(std::string word);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3121COUNTTHENUMBEROFSPECIALCHARACTERSII_H