//
// Created by saeed on 11/22/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3190FINDMINIMUMOPERATIONSTOMAKEALLELEMENTSDIVISIBLEBYTHREE_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3190FINDMINIMUMOPERATIONSTOMAKEALLELEMENTSDIVISIBLEBYTHREE_H
#include <vector>


class LeetCode3190FindMinimumOperationsToMakeAllElementsDivisibleByThree {
    int minimumOperations(std::vector<int>& nums) ;
};




#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3190FINDMINIMUMOPERATIONSTOMAKEALLELEMENTSDIVISIBLEBYTHREE_H
