//
// Created by Saeed Jannati on 2/24/2026 A.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1022SUMOFROOTTOLEAFBINARYNUMBERS_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1022SUMOFROOTTOLEAFBINARYNUMBERS_H


struct TreeNode;

class LeetCode1022SumOfRootToLeafBinaryNumbers {

    int sumRootToLeaf(TreeNode* root);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1022SUMOFROOTTOLEAFBINARYNUMBERS_H