//
// Created by saeed on 10/9/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3494FINDTHEMINIMUMAMOUNTOFTIMETOBREWPOTIONS_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3494FINDTHEMINIMUMAMOUNTOFTIMETOBREWPOTIONS_H
#include <vector>


class LeetCode3494FindTheMinimumAmountOfTimeToBrewPotions {
private:
    long long minTime(std::vector<int>& skill, std::vector<int>& mana);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3494FINDTHEMINIMUMAMOUNTOFTIMETOBREWPOTIONS_H