//
// Created by saeed on 9/29/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1039MINIMUMSCORETRIANGULATIONOFPOLYGON_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1039MINIMUMSCORETRIANGULATIONOFPOLYGON_H
#include <vector>


class LeetCode1039MinimumScoreTriangulationOfPolygon {
    int minScoreTriangulation(std::vector<int>& values) ;
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1039MINIMUMSCORETRIANGULATIONOFPOLYGON_H