//
// Created by Saeed Jannati on 2/7/2026 A.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1653MINIMUMDELETIONSTOMAKESTRINGBALANCED_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1653MINIMUMDELETIONSTOMAKESTRINGBALANCED_H
#include <string>


class LeetCode1653MinimumDeletionsToMakeStringBalanced {
    int minimumDeletions(std::string s);
};




#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1653MINIMUMDELETIONSTOMAKESTRINGBALANCED_H
