//
// Created by saeed on 1/2/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE961NREPEATEDELEMENTINSIZE2NARRAY_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE961NREPEATEDELEMENTINSIZE2NARRAY_H
#include <vector>


class LeetCode961NRepeatedElementInSize2NArray {
    int repeatedNTimes(std::vector<int>& nums);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE961NREPEATEDELEMENTINSIZE2NARRAY_H