//
// Created by saeed on 10/10/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3147TAKINGMAXIMUMENERGYFROMTHEMYSTICDUNGEON_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3147TAKINGMAXIMUMENERGYFROMTHEMYSTICDUNGEON_H
#include <vector>


class LeetCode3147TakingMaximumEnergyFromTheMysticDungeon {
private:
    int maximumEnergy(std::vector<int>& energy, int k);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3147TAKINGMAXIMUMENERGYFROMTHEMYSTICDUNGEON_H