//
// Created by saeed on 1/4/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1411NUMBEROFWAYSTOPAINTNX3GRID_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1411NUMBEROFWAYSTOPAINTNX3GRID_H


class LeetCode1411NumberOfWaysToPaintNx3Grid {
    int numOfWays(int n);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1411NUMBEROFWAYSTOPAINTNX3GRID_H