//
// Created by saeed on 2/12/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3713LONGESTBALANCEDSUBSTRINGI_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3713LONGESTBALANCEDSUBSTRINGI_H
#include <string>


class LeetCode3713LongestBalancedSubstringI {
    int longestBalanced(std::string s) ;
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3713LONGESTBALANCEDSUBSTRINGI_H