//
// Created by saeed on 5/29/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3300MINIMUMELEMENTAFTERREPLACEMENTWITHDIGITSUM_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3300MINIMUMELEMENTAFTERREPLACEMENTWITHDIGITSUM_H
#include <vector>


class LeetCode3300MinimumElementAfterReplacementWithDigitSum {
    int minElement(std::vector<int>& nums);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3300MINIMUMELEMENTAFTERREPLACEMENTWITHDIGITSUM_H