//
// Created by saeed on 3/19/25.
//

#ifndef LEETCODE3191MINIMUMOPERATIONSTOMAKEBINARYARRAYELEMENTSEQUALTOONEI_H
#define LEETCODE3191MINIMUMOPERATIONSTOMAKEBINARYARRAYELEMENTSEQUALTOONEI_H
#include <vector>


class LeetCode3191MinimumOperationsToMakeBinaryArrayElementsEqualToOneI {
    int minOperations(std::vector<int>& nums);
};



#endif //LEETCODE3191MINIMUMOPERATIONSTOMAKEBINARYARRAYELEMENTSEQUALTOONEI_H
