//
// Created by saeed on 12/10/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3577COUNTTHENUMBEROFCOMPUTERUNLOCKINGPERMUTATIONS_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3577COUNTTHENUMBEROFCOMPUTERUNLOCKINGPERMUTATIONS_H
#include <vector>


class LeetCode3577CountTheNumberOfComputerUnlockingPermutations {
    int countPermutations(std::vector<int>& complexity);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3577COUNTTHENUMBEROFCOMPUTERUNLOCKINGPERMUTATIONS_H