//
// Created by saeed on 11/26/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE2435PATHSINMATRIXWHOSESUMISDIVISIBLEBYK_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE2435PATHSINMATRIXWHOSESUMISDIVISIBLEBYK_H
#include <vector>


class LeetCode2435PathsInMatrixWhoseSumIsDivisibleByK {
    int numberOfPaths(std::vector<std::vector<int>>& grid, int k);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE2435PATHSINMATRIXWHOSESUMISDIVISIBLEBYK_H