//
// Created by saeed on 11/16/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1513NUMBEROFSUBSTRINGSWITHONLY1S_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1513NUMBEROFSUBSTRINGSWITHONLY1S_H
#include <string>


class LeetCode1513NumberOfSubstringsWithOnly1s {
private:
    int numSub(std::string s) ;
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1513NUMBEROFSUBSTRINGSWITHONLY1S_H