//
// Created by saeed on 11/9/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE2169COUNTOPERATIONSTOOBTAINZERO_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE2169COUNTOPERATIONSTOOBTAINZERO_H


class LeetCode2169CountOperationsToObtainZero {
    int countOperations(int num1, int num2);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE2169COUNTOPERATIONSTOOBTAINZERO_H