//
// Created by Saeed Jannati on 5/10/2026 A.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE2770MAXIMUMNUMBEROFJUMPSTOREACHTHELASTINDEX_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE2770MAXIMUMNUMBEROFJUMPSTOREACHTHELASTINDEX_H
#include <vector>


class LeetCode2770MaximumNumberOfJumpsToReachTheLastIndex {
private:
    int maximumJumps(std::vector<int>& nums, int target);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE2770MAXIMUMNUMBEROFJUMPSTOREACHTHELASTINDEX_H