//
// Created by saeed on 10/6/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1432MAXDIFFERENCEYOUCANGETFROMCHANGINGANINTEGER_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1432MAXDIFFERENCEYOUCANGETFROMCHANGINGANINTEGER_H
#include "BaseProblem.h"


class LeetCode1432MaxDifferenceYouCanGetFromChangingAnInteger: BaseProblem {
private:
    int maxDiff(int num);
public:
    void Run() override;
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1432MAXDIFFERENCEYOUCANGETFROMCHANGINGANINTEGER_H