//
// Created by saeed on 11/13/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3228MAXIMUMNUMBEROFOPERATIONSTOMOVEONESTOTHEEND_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3228MAXIMUMNUMBEROFOPERATIONSTOMOVEONESTOTHEEND_H
#include <string>


class LeetCode3228MaximumNumberOfOperationsToMoveOnesToTheEnd {
private:
    int maxOperations(std::string s);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3228MAXIMUMNUMBEROFOPERATIONSTOMOVEONESTOTHEEND_H