//
// Created by saeed on 10/19/25.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE1625LEXICOGRAPHICALLYSMALLESTSTRINGAFTERAPPLYINGOPERATIONS_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE1625LEXICOGRAPHICALLYSMALLESTSTRINGAFTERAPPLYINGOPERATIONS_H
#include <string>


class LeetCode1625LexicographicallySmallestStringAfterApplyingOperations {
private:
    std::string findLexSmallestString(std::string s, int a, int b);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE1625LEXICOGRAPHICALLYSMALLESTSTRINGAFTERAPPLYINGOPERATIONS_H