//
// Created by saeed on 6/4/26.
//

#ifndef LEETCODEPROBLEMSCMAKE_LEETCODE3751TOTALWAVINESSOFNUMBERSINRANGEI_H
#define LEETCODEPROBLEMSCMAKE_LEETCODE3751TOTALWAVINESSOFNUMBERSINRANGEI_H


class LeetCode3751TotalWavinessOfNumbersInRangeI {
private:
    int totalWaviness(int num1, int num2);
};


#endif //LEETCODEPROBLEMSCMAKE_LEETCODE3751TOTALWAVINESSOFNUMBERSINRANGEI_H